source 'https://rubygems.org'

gem 'eventmachine'
gem 'thin', '~> 1.8'
gem 'redis'
gem 'sinatra', '~> 2.1'
gem 'sinatra-contrib', '~> 2.1'
gem 'mustermann', '~> 2.0'
gem 'rake'
gem 'json'
gem 'ruby-ip'
gem 'pg', '~> 1.5'
gem 'sequel', '~> 5.6'
gem 'sequel_pg', '~> 1.15'
gem 'ruby-enum'
gem 'dotenv'
gem 'sidekiq'
gem 'jwt'
gem 'terminal-table'
gem 'time_difference'
gem 'activesupport'
gem 'mini_magick', '~> 4.11'

gem 'volgactf-final-checker-result', '~> 1.0.0'
